spring.datasource.url=jdbc:h2:file:./data/demo-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2
assets.csv.file=top_1000_coins.csv
history.csv.file=coin_details.csv
ta.summary.file=data/TA_top_1000_summary.csv

server.port=${PORT:8080}
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true



app.import.enabled=${APP_IMPORT_ENABLED:true}



